### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by dckc** [dckc/awesome-ocap#22]
Sat 1400utc

Zoom link will be here

**Comment by dckc** [comment]
not great devex:

```
$ agoric
/home/connolly/projects/agoric/agoric-sdk/packages/agoric-cli/lib/entrypoint.js:6
import 'esm';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
(base) ~
```

IOU agoric-sdk issue

**Comment by dckc** [comment]
## kc-strip on devnode: no joy

struggled to get my [kc-strip node set-up](https://github.com/dckc/madmode-blog/tree/master/projects/kc-strip) working on [devnet](https://devnet.explorer.agoric.net/validators)


https://gist.github.com/dckc/b2823f801f72fdc2a69bb07572141396 was due to version mis-match, I think.

but then with 6.0.0, I got

```
Error: failed to get address from Keybase: validator.info: key not found [agoric-labs/cosmos-sdk@v0.43.0-rc2.agoric/crypto/keyring/keyring.go:462]
```

**Comment by dckc** [comment]
notes from today:

@jimscarver said he has 2 goals:
  1. to build a leaderless organization exhibiting cooperative intelligence
  2. _something about physics..._

We have been working on (1) in rgov. We lamented that folks are re-inventing [rgov/WorkingGroup.rho](https://github.com/rchain-community/rgov/blob/master/WorkingGroup.rho).

See also:
 - [assetStore - a multi token standard · Issue #30 · rchain/rchip-proposals](https://github.com/rchain/rchip-proposals/issues/30) esp [my Aug 9 request to use ERTP](https://github.com/rchain/rchip-proposals/issues/30#issuecomment-895289277)

I went over some recent work:
 - [ingest 2021 Q2 balance sheet into RVote agenda (WIP)](https://github.com/rchain/reference/pull/63)

background:
   - [Features | GnuCash](https://www.gnucash.org/new_features-4.0.phtml)
   - [MadMode: Got my data back from Mint, thanks to GnuCash/mysql](https://www.madmode.com/2012/02/got-my-data-back-from-mint-thanks-to.html)

We reviewed [docs: fixed incorrect guide for setting up eslint to work with jessie by tgrecojs · \#607 · Agoric/documentation](https://github.com/Agoric/documentation/pull/607) by [updating RChain-API to use @jessie-check](https://github.com/rchain-community/rchain-api/commit/77a25d7c00c039833cfaa078dfbcc92d7e431484)

I tried to use the "flow-sensitive analysis" in jstar to [define harden rules using escape analysis? \#35](https://github.com/agoric-labs/jessica/issues/35) but we got stuck at:

 - [jstar extract failed with: Cannot run program "sh" · Issue \#1 · kaist\-plrg/jstar](https://github.com/kaist-plrg/jstar/issues/1)

@tgrecojs is trying to run the Agoric pegasus IBC demo (aka  - [sending a payment over IBC to agoricdev-6 from cosmoshub-test](https://gist.github.com/dckc/9a336a983a30a20751b38380e3308fab) ), but on his M1 mac he hit [dyld error when executing scenarios within cosmic\-swingset makefile · Issue \#4140 · Agoric/agoric\-sdk](https://github.com/Agoric/agoric-sdk/issues/4140). We tried working around it using:

 - [dckc/agoric-gitpod-nix: agoric-sdk on Gitpod: zero-install BLD tools](https://github.com/dckc/agoric-gitpod-nix)

While the pod was spinning up, I noted:

 - [CapTP using RhoTypes.proto under @agoric/marshal · Issue #95 · rchain-community/rchain-api](https://github.com/rchain-community/rchain-api/issues/95)
 - [RChain multi-shard DEX architecture compared to Osmosis on Cosmos / Agoric IBC · Issue #16 · rchain-community/rstake](https://github.com/rchain-community/rstake/issues/16)
 - [Commonwealth – Agoric](https://commonwealth.im/agoric/)
   - [Proposal for network decentralization · Issue #4294 · Agoric/agoric-sdk](https://github.com/Agoric/agoric-sdk/issues/4294)

the pod did spin up, but then we adjourned; we hope @tgrecojs makes progress this way.

not discussed, but in an open tab:
 - [MadMode: Introducing Capabilities to the Next Generation](https://www.madmode.com/2016/03-park-talk.html)

**Comment by dckc** [comment]
Thanks for hosting today, @jimscarver . Good to see you @9rb . Thanks for all the questions that prompted me to provide much better context, @cwebber . As we discussed, it should make the recording (to appear) much more valuable. And @Bill-Kunj put in an appearance toward the end.

_Raw tab dump follows; here's hoping I find time to edit these notes._

Demo (internal) of RUN protocol governance · Issue #4348 · Agoric/agoric-sdk: https://github.com/Agoric/agoric-sdk/issues/4348
Office Hours: patterns of cooperation without vulnerability · Issue #22 · dckc/awesome-ocap: https://github.com/dckc/awesome-ocap/issues/22
RChain multi-shard DEX architecture compared to Osmosis on Cosmos / Agoric IBC · Issue #16 · rchain-community/rstake: https://github.com/rchain-community/rstake/issues/16
CapTP using RhoTypes.proto under @agoric/marshal · Issue #95 · rchain-community/rchain-api: https://github.com/rchain-community/rchain-api/issues/95
dckc/awesome-ocap: Awesome Object Capabilities and Capability Security: https://github.com/dckc/awesome-ocap
CapTP using RhoTypes.proto under @agoric/marshal · Issue #95 · rchain-community/rchain-api: https://github.com/rchain-community/rchain-api/issues/95
Demo: create a token and add it to the AMM / Swap · Issue #616 · Agoric/documentation: https://github.com/Agoric/documentation/issues/616
Agoric DEX tools: ERTP, Zoe, ... · Issue #4 · rchain-community/js2rho: https://github.com/rchain-community/js2rho/issues/4
Voting in Rholang - Google Slides: https://docs.google.com/presentation/d/1LLwejP0QdhHwhjYd-LFIPBblj1owjBGHBgL_EWh80V8/edit#slide=id.g9c72ba371b_0_1353
Map of zones - Cosmos network explorer: https://mapofzones.com/?testnet=false&period=24&tableOrderBy=totalIbcTxs&tableOrderSort=desc
ocapn/ocapn: General planning and documentation repository for the OCapN protocol suite for distributed networked objects: https://github.com/ocapn/ocapn
Tech Stack - Agoric: https://agoric.com/tech/
Voting Power Distribution on Cosmos Hub | The Big Dipper: https://devnet.explorer.agoric.net/voting-power-distribution
Home | Uniswap Protocol: https://uniswap.org/
Uniswap Interface: https://app.uniswap.org/#/swap?chain=mainnet
Uniswap Info: https://info.uniswap.org/#/
Hash Time Locked Contracts - Bitcoin Wiki: https://en.bitcoin.it/wiki/Hash_Time_Locked_Contracts#:~:text=A%20Hash%20Time%20Locked%20Contract,returning%20it%20to%20the%20payer.
Guile security vulnerability w/ listening on localhost + port (with fix): https://lists.gnu.org/archive/html/guile-user/2016-10/msg00007.html
E in a Walnut: http://www.skyhunter.com/marcs/ewalnut.html
Petname Systems -- Spritely: https://spritelyproject.org/news/petname-systems.html
Agoric Core Economy: https://treasury.agoric.app/swap
2 Glow Tutorial: https://glow-lang.org/docs/Glow_Tutorial.html
Chialisp: https://chialisp.com/
ZCash Gardening Club: Jessie, IBC, ... · Issue #628 · Agoric/documentation: https://github.com/Agoric/documentation/issues/628
Mina Protocol | The World's Lightest Blockchain Protocol: https://minaprotocol.com/
Propagators, Brainy, and Spritely - MetaFox Talks - YouTube: https://www.youtube.com/watch?v=jI8gA68OXLM&list=PLvf2RZCNC-UA6E8RjpebCnDGlsZN93E7b&index=2
Propagation Networks: A Flexible and Expressive Substrate for Computation: https://dspace.mit.edu/handle/1721.1/49525
lgilpin-PhD-EECS-Sept2020.pdf: https://groups.csail.mit.edu/mac/users/gjs/lgilpin-PhD-EECS-Sept2020.pdf

**Comment by dckc** [comment]
Thanks for hosting again, @jimscarver

After a bit of introductions, we did get around to your request to discuss **building a [RChain] token exchange and cross chain/shard  swaps using agoric**.

And I showed a recording of the **"start the Agoric economy" governance process demo** that didn't quite work last time.

dckc/awesome-ocap: Awesome Object Capabilities and Capability Security: https://github.com/dckc/awesome-ocap#os
Demo: create a token and add it to the AMM / Swap · Issue #616 · Agoric/documentation: https://github.com/Agoric/documentation/issues/616
RChain multi-shard DEX architecture compared to Osmosis on Cosmos / Agoric IBC · Issue #16 · rchain-community/rstake: https://github.com/rchain-community/rstake/issues/16
Home · dckc/awesome-ocap Wiki: https://github.com/dckc/awesome-ocap/wiki
js2rho/examples at master · dckc/js2rho: https://github.com/dckc/js2rho/tree/master/examples
Genode - Release notes for the Genode OS Framework 22.02: https://genode.org/documentation/release-notes/22.02
MadMode: Rosetta Stone: Taking propositions-as-types to the next level | Code: https://www.madmode.com/2020/grok-idris-ct.html
Introducing Fractally — The next generation of DAOs | by Daniel Larimer | goƒractally | Jan, 2022 | Medium: https://medium.com/gofractally/introducing-fractally-the-next-generation-of-daos-7c94981514d8
staking pools need separate rewards channel when bonding · Issue #32 · rchain/rchip-proposals: https://github.com/rchain/rchip-proposals/issues/32
RChain light client? Merkle tree to transactions? (IBC for RChain?) · Issue #35 · rchain/rchip-proposals: https://github.com/rchain/rchip-proposals/issues/35
rchain/CasperMessage.proto at dev · rchain/rchain: https://github.com/rchain/rchain/blob/dev/models/src/main/protobuf/CasperMessage.proto
RChain: https://rchain.coop/#roadmap
JavaScript Framework for Secure Distributed Computing | Beta: https://agoric.com/documentation/guides/js-programming/
(185) Distributed Programming for a Decentralized World - YouTube: https://www.youtube.com/playlist?list=PLzDw4TTug5O1oHRbp2HkcvKABAY9FKsmG
2 way reliable messaging (VatTP) layer · Issue #94 · rchain-community/rchain-api: https://github.com/rchain-community/rchain-api/issues/94
boot gov demo - Zoom: https://agoric.zoom.us/rec/play/RJ-h-FBIDHWjx1FzcYulGGBZucRahu7LPNqXo6VzH-9QVa_LFtcgK9W7t7nEk8AhtkZL6c4RqPNXUccI.q381Tb97zX9J2YU8?continueMode=true&_x_zm_rtaid=Yx6KEt-zRpmiju5CzUA_Gw.1646492593769.cf613e17d7f632f36f5ed16091eb1a95&_x_zm_rhtaid=444

**Comment by jimscarver** [comment]
> Thanks for hosting again, @jimscarver
> 
> After a bit of introductions, we did get around to your request to discuss **building a [RChain] token exchange and cross chain/shard swaps using agoric**.
> 
Video https://youtu.be/262MYn4wpHU

**Comment by tgrecojs** [comment]
*comment planned to be subject to edits*

topic dump related to hardened js / Zoe contract testing. 


1. Best way to approach setup testing environment for Zoe. 
- Changes in Zoe API led to my setupZcf function breaking. 
- [https://github.com/Agoric/agoric-sdk/blame/4c4da6a7ae76aebbff2af48613008978eb04462b/packages/zoe/test/unitTests/zcf/setupZcfTest.js#L3](https://github.com/Agoric/agoric-sdk/blame/4c4da6a7ae76aebbff2af48613008978eb04462b/packages/zoe/test/unitTests/zcf/setupZcfTest.js#L35)5

Seems like a lot of boilerplate code is used. wondering if it would be effective to take an approach in which a test-specific code is embedded within an abstract data type in order to provide an interface for handling Zoe test setup. 


```jsx 
const { zoeService: zoe, feeMintAccess } = makeZoeKit(fakeVatAdmin.admin); 
const bundle = await bundleSource(contractRoot); 
fakeVatAdmin.vatAdminState.installBundle('b1-contract', bundle); 
const installation = await E(zoe).installBundleID('b1-contract'); 
const { creatorFacet, instance } = await E(zoe).startInstance( 
installation, 
issuerKeywordRecord, 
terms, 
); 
// In case a second zcf is needed 
const { creatorFacet: creatorFacet2, instance: instance2 } = await E( 
zoe, 
).startInstance(installation, issuerKeywordRecord, terms);
``` 

1. endo/init + migration of other hardened js libraries from agoric to end
3. Using test runners like quokka and wallabyjs to test hardened-js → issues arise which i believe stem from babel / initialization of lockdown function

**Comment by dckc** [comment]
Looks like the agoric-sdk -> endo migration is in https://github.com/endojs/endo/issues/506 , https://github.com/Agoric/agoric-sdk/pull/4427 and points nearby.

**Comment by tgrecojs** [comment]
https://github.com/tgrecojs/wallabyjs-hardenedjs

**Comment by dckc** [comment]
today's topics, mostly:

 - endo vs. wallaby
 - rholang crash course
 - cross-chain messaging https://github.com/rchain-community/rchain-api/issues/95

tab dump:
https://gist.github.com/dckc/393baa13b32d7301af412cb8ba5a242a

**Comment by jimscarver** [comment]
> today's topics, mostly:

https://youtu.be/Ue5TWcXktH0

**Comment by dckc** [comment]
raw tab dump from today follows; here's hoping I manage to edit the story a bit...

dckc/awesome-ocap: Awesome Object Capabilities and Capability Security: https://github.com/dckc/awesome-ocap
Facet · dckc/awesome-ocap Wiki: https://github.com/dckc/awesome-ocap/wiki/Facet
Mark S. Miller, Immunity from Viruses, Safety from Geeks Bearing Gifts (May 9, 2002) - YouTube: https://www.youtube.com/watch?v=KoM_aCuFk1w
ingest 2021 Q2 balance sheet into RVote agenda (WIP) by dckc · Pull Request #63 · rchain/reference: https://github.com/rchain/reference/pull/63
Agoric (@agoric) / Twitter: https://twitter.com/agoric
Gateway Conference & Hackathon: https://gateway.events/
agoric-sdk/packages at master · Agoric/agoric-sdk: https://github.com/Agoric/agoric-sdk/tree/master/packages
Happy BLD distribution day! Which validator to delegate to? - YouTube: https://www.youtube.com/watch?v=HFECe7KGUeM
CoinList Wiki on Twitter: "$BLD coming to your wallets soon 😍 Tokens will be locked but can be staked! Rewards are unlocked! 🔥 Thanks to @agoric - the Javascript Smart Contract infrastructure plarform that aims to push blockchain programming to mainstream web2.0 devs. 🎉 #Agoric #TokenSale #BLD #Web3 https://t.co/lwNkvbs5hc" / Twitter: https://twitter.com/CoinlistWiki/status/1509476879148978182
Demo (internal) of RUN protocol governance · Issue #4348 · Agoric/agoric-sdk: https://github.com/Agoric/agoric-sdk/issues/4348
The Mother of All Demos - Wikipedia: https://en.wikipedia.org/wiki/The_Mother_of_All_Demos
Zoe | Beta: https://agoric.com/documentation/zoe/api/zoe.html#e-zoe-getinvitationdetails-invitation
Cosmos Validator List | The Big Dipper: https://main.explorer.agoric.net/validators?sort=uptime&dir=1
js2rho/capTPTool.js at captp · rchain-community/js2rho: https://github.com/rchain-community/js2rho/blob/captp/lib/capTPTool.js
Our Story - Agoric: https://agoric.com/about/
Using Durable Objects · Cloudflare Workers docs: https://developers.cloudflare.com/workers/learning/using-durable-objects/
CapTP using RhoTypes.proto under @agoric/marshal · Issue #95 · rchain-community/rchain-api: https://github.com/rchain-community/rchain-api/issues/95
Osmosis: TVL and stats - DefiLlama: https://defillama.com/protocol/osmosis
April 13-14 2022 - Paris Blockchain Week Summit - Build The Next Web: https://www.pbwsummit.com/
Dan Connolly's Index of Events: https://www.w3.org/People/Connolly/events/
ACTION-497: Prepare us for a teleconference with IETF-IAB on possible prague IETF presentation. - Technical Architecture Group Tracker: https://www.w3.org/2001/tag/group/track/actions/497
260 Dec 8 Community Debrief - Tech update 201, Theo NFT demo, Foresight Institute, Venus roadmap - RChain Blog: https://blog.rchain.coop/2021/12/10/debrief-260/

**Comment by dckc** [comment]
tab dump:

Office Hours: patterns of cooperation without vulnerability · Issue #22 · dckc/awesome-ocap: https://github.com/dckc/awesome-ocap/issues/22
ocap bill of rights · Issue #17 · dckc/awesome-ocap: https://github.com/dckc/awesome-ocap/issues/17
meeting Jim Whitescarver - 1991? 1995? · Issue #159 · dckc/madmode-blog: https://github.com/dckc/madmode-blog/issues/159
Commonwealth – Agoric: https://commonwealth.im/agoric/discussion/4295-devnet-proposal-to-deploy-runstake-passed
Agoric || Welcome aboard!: https://wallet.agoric.app/
Lunie 3: https://devnet.staking.agoric.app/proposals
Introduction | Keplr wallet: https://docs.keplr.app/
Post | Feed | LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6919311765688205312/
Post | Feed | LinkedIn: https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6919720783141359616/
W3C mailing list search service: https://www.w3.org/Search/Mail/Public/advanced_search?keywords=whitescarver&hdr-1-name=subject&hdr-1-query=&hdr-2-name=from&hdr-2-query=&hdr-3-name=message-id&hdr-3-query=&period_month=&period_year=&index-type=g&index-grp=Public__FULL&type-index=&resultsperpage=20&sortby=date-asc
W3C Process Document: https://www.w3.org/2021/Process-20211102/
Re: Client-side highlighting; tag proposal from James Whitescarver on 1995-03-14 (www-talk@w3.org from March to April 1995): https://lists.w3.org/Archives/Public/www-talk/1995MarApr/0141.html
www-talk from November to December 1991: documents, files, types, and access methods: https://lists.w3.org/Archives/Public/www-talk/1991NovDec/0015.html
MadMode: Smart Contracts for Health Research Data Sharing | Code: https://www.madmode.com/2018/boulder-bos.html
MadMode: dreaming big at the RChain Governance Forum | Code: https://www.madmode.com/2018/rchain-gov-forum-sea
MadMode: Smart Contracts and Capabilities Up Close | Code: https://www.madmode.com/2017/rchain-dev-retreat.html
Aaron Swartz - Wikipedia: https://en.wikipedia.org/wiki/Aaron_Swartz
The Mother of All Demos, presented by Douglas Engelbart (1968) - YouTube: https://www.youtube.com/watch?v=yJDv-zdhzMY
When Encryption Was a Crime: The 1990s Battle for Free Speech in Software - YouTube: https://www.youtube.com/watch?v=lv8OFSWZkGs&list=PLBuns9Evn1w-T2RwqMhUnTZbTTe-M-g42&index=3
How to evaluate Web Applications security designs? | W3C Blog: https://www.w3.org/blog/2008/12/web-applications-security-requ/
MadMode: Introducing Capabilities to the Next Generation | Code: https://www.madmode.com/2016/03-park-talk.html
eval() - JavaScript | MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval
RChain: https://rchain.coop/
rchain-community/rgov: RChain liquid democracy demo: capability sharing, mailbox, directory, chat, ...: https://github.com/rchain-community/rgov
MadMode: RChain Blues | Code: https://www.madmode.com/2019/rchain-blues.html
feat(subm): 1 BLD request status google sheet by dckc · Pull Request #44 · Agoric/testnet-notes: https://github.com/Agoric/testnet-notes/pull/44
Install RUN Protocol Preview release in devnet on April 22 · Issue #5062 · Agoric/agoric-sdk: https://github.com/Agoric/agoric-sdk/issues/5062

**Comment by dckc** [comment]
tab dump for today:

Office Hours: patterns of cooperation without vulnerability · Issue #22 · dckc/awesome-ocap: https://github.com/dckc/awesome-ocap/issues/22
Request 1 BLD as in Zoe using ag-solo plugins · Issue #45 · Agoric/testnet-notes: https://github.com/Agoric/testnet-notes/issues/45
dapp-oracle/spawn.js at main · Agoric/dapp-oracle: https://github.com/Agoric/dapp-oracle/blob/main/api/spawn.js
eventual send with E() | Beta: https://agoric.com/documentation/guides/js-programming/eventual-send.html#eventual-send
avajs/ava: Node.js test runner that lets you develop with confidence 🚀: https://github.com/avajs/ava
Tech Stack - Agoric: https://agoric.com/tech/
Map of zones - Cosmos network explorer: https://mapofzones.com/?testnet=false&period=24&tableOrderBy=ibcVolume&tableOrderSort=desc
Cosmos SDK - Cosmos Network: https://v1.cosmos.network/sdk
Big Dipper | Agoric Block Explorer: https://agoric.bigdipper.live/
Big Dipper | Cosmos Explorer presented by Forbole: https://crypto-org.bigdipper.live/
Gravity DEX - Ecosystem - Cosmos: The Internet of Blockchains: https://cosmos.network/gravity-dex/?utm_source=forbole&utm_medium=referral&utm_campaign=gravitydex_launch&utm_id=gravitydex_launch&utm_term=organic&utm_content=block_explorer
remote channels and deploys for cross-shard interaction · Issue #45 · rchain/rchip-proposals: https://github.com/rchain/rchip-proposals/issues/45
assetStore - a multi token standard · Issue #30 · rchain/rchip-proposals: https://github.com/rchain/rchip-proposals/issues/30
How and why RChain should use Agoric’s NFT design - Google Slides: https://docs.google.com/presentation/d/19JHhdEXrG14usHN7aCVmhs_He-jhMm48acmdwe0ZgBE/edit#slide=id.ge22cb7b809_0_249
rgov/RevIssuer.rho at master · rchain-community/rgov: https://github.com/rchain-community/rgov/blob/master/rholang/core/RevIssuer.rho
CapTP using RhoTypes.proto under @agoric/marshal · Issue #95 · rchain-community/rchain-api: https://github.com/rchain-community/rchain-api/issues/95
inter-shard communication · Issue #47 · r-publishing/rpub-mono: https://github.com/r-publishing/rpub-mono/issues/47
endo/captp.js at master · endojs/endo: https://github.com/endojs/endo/blob/master/packages/captp/src/captp.js
inter-shard communication · Issue #47 · r-publishing/rpub-mono: https://github.com/r-publishing/rpub-mono/issues/47
2022-03-12 dan's office hours, agoric, capTP to rholang gateway - YouTube: https://www.youtube.com/watch?v=Ue5TWcXktH0
CapTP: The 4 Tables: http://www.erights.org/elib/distrib/captp/4tables.html

**Comment by dckc** [comment]
tab dump from today:

Office Hours: patterns of cooperation without vulnerability · Issue #22 · dckc/awesome-ocap: https://github.com/dckc/awesome-ocap/issues/22
staking pools need separate rewards channel when bonding · Issue #32 · rchain/rchip-proposals: https://github.com/rchain/rchip-proposals/issues/32
assetStore - a multi token standard · Issue #30 · rchain/rchip-proposals: https://github.com/rchain/rchip-proposals/issues/30
Issues · rchain/rchain: https://github.com/rchain/rchain/issues?q=is%3Aissue+is%3Aopen+token
how to make a contract that executes on receipt of REV? · Issue #31 · rchain/rchip-proposals: https://github.com/rchain/rchip-proposals/issues/31
delegated proof of stake pure - Google Search: https://www.google.com/search?q=delegated+proof+of+stake+pure&oq=delegated+proof+of+stake+pure&aqs=chrome..69i57.5713j0j1&sourceid=chrome&ie=UTF-8
What Is Proof of Stake (PoS)? PoS Types Examined | Gemini: https://www.gemini.com/cryptopedia/proof-of-stake-delegated-proof-of-stake-consensus-mechanism#section-pure-proof-of-stake

Use WalletConnect · Issue #2962 · Agoric/agoric-sdk: https://github.com/Agoric/agoric-sdk/issues/2962
Home - WalletConnect: https://walletconnect.com/
Agoric/documentation: User documentation: https://github.com/Agoric/documentation
JavaScript Framework for Secure Distributed Computing | Beta: https://agoric.com/documentation/guides/js-programming/
Distributed Programming for a Decentralized World - YouTube: https://www.youtube.com/playlist?list=PLzDw4TTug5O1oHRbp2HkcvKABAY9FKsmG
NoahSaso/cosmodal: https://github.com/NoahSaso/cosmodal
primordialsoup/interpreter.cc at master · newspeaklanguage/primordialsoup: https://github.com/newspeaklanguage/primordialsoup/blob/master/vm/interpreter.cc#L744-L754
Scratch - Imagine, Program, Share: https://scratch.mit.edu/
Alan Kay - Wikipedia: https://en.wikipedia.org/wiki/Alan_Kay
SmallTalk to rholang translator? · Issue #17 · rchain-community/js2rho: https://github.com/rchain-community/js2rho/issues/17
hierarchical NFTs? · Issue #5 · fabcotech/rchain-token: https://github.com/fabcotech/rchain-token/issues/5
idea: static analysis for unexpected throws · Issue #40 · sukyoung/safe: https://github.com/sukyoung/safe/issues/40#issuecomment-1165597550

**Comment by dckc** [comment]
last week:

[2022\-07\-16 Dan's OCAPS early scheme, syndicate\-lang, juno \- YouTube](https://www.youtube.com/watch?v=ASwvdksleeA)

ocaps in Juno / cosmwasm? · Issue #29 · dckc/awesome-ocap
https://github.com/dckc/awesome-ocap/issues/29

Ancient Web Browsers | tweedy
http://9p.sdf.org/who/tweedy/ancient_browsers/

EMail Msg <9211212233.AA16031@njitgw.njit.edu>
http://ksi.cpsc.ucalgary.ca/archives/WWW-TALK/www-talk-1992.messages/344.html

XcRichText -- A Motif Widget for RTF
https://www.w3.org/People/Connolly/support/XcRichText.html

Protocol specification - The Synit Manual
https://synit.org/book/protocol.html

Byte Magazine Volume 06 Number 08 - Smalltalk : Free Download, Borrow, and Streaming : Internet Archive
https://archive.org/details/byte-magazine-1981-08/page/n5/mode/2up

The Spritely Networked Communities Institute -- Spritely Institute
https://spritely.institute/

SDF Public Access UNIX System - Free Shell Account and Shell Access
https://sdf.org/?faq?UNIX?06

Whole Earth Catalog - Wikipedia
https://en.wikipedia.org/wiki/Whole_Earth_Catalog

MadMode: Closing music sharing loops with Amazon Cloud Player and iTunes home sharing | Code
https://www.madmode.com/2011/04/closing-music-sharing-loops-with-amazon.html

Juno - Smart Contracts Zone
https://www.junochainvalidate.live/

**Comment by jimscarver** [comment]
Can we discuss the DCF grant  proposal in the morning meeting.  Would another time be better? 

Radically decentralized cooperation at scale

The aim of this project is user centric voluntary cooperation by consent among autonomous individuals and groups at scale in spite of differences in language, political, religious or philosophical disagreements employing patterns of successful decentralized organization and collective intelligence best practices.

Reification and ownership of capabilities with conditional delegation can facilitate capitalization on the abundance of underutilized human potential

Regenerative economics (UBI plus cooperation/value incentives?) enables viability of the user centric system.

**Comment by dckc** [comment]
Perhaps another week. Tomorrow I'm not available.

**Comment by dckc** [comment]
## Property Testing in Guile Scheme

today's episode: [Property testing library for guile? for Zoe escrow as goblins \- Spritely Networked Communities Institute](https://community.spritely.institute/t/property-testing-library-for-guile-for-zoe-escrow-as-goblins/536)

with a couple colleagues from [ocapn](https://github.com/ocapn/ocapn)

hosted on jitsi

### It works!

```
scheme@(guile-user)> (load "qc.scm")
Falsifiable after 4 tests.
Seed: 1062349682
toppings = (olives tomato-slices peppers)
$6 = #f
```

### devtools from guix

```console
$ guix shell emacs emacs-geiser-guile
```

## tab dump

[SPIKE: toward correct-by-construction Zoe2 escrow by dckc · Pull Request #8184 · Agoric/agoric-sdk](https://github.com/Agoric/agoric-sdk/pull/8184)
[The Heart of Spritely: Distributed Objects and Capability Security](https://spritely.institute/static/papers/spritely-core.html#appendix-using-goblins-wisp)
[ocapn/ocapn: General planning and documentation repository for the OCapN protocol suite for distributed networked objects](https://github.com/ocapn/ocapn)
[Purse Object | Agoric Documentation](https://docs.agoric.com/reference/ertp-api/purse.html#apurse-getallegedbrand)
[Property testing library for guile? for Zoe escrow as goblins - Spritely Networked Communities Institute](https://community.spritely.institute/t/property-testing-library-for-guile-for-zoe-escrow-as-goblins/536)
[Guile-QuickCheck – Ngyro](https://ngyro.com/software/guile-quickcheck.html)
[ProVerif](https://bblanche.gitlabpages.inria.fr/proverif/)
[Using Guile Modules (Guile Reference Manual)](https://www.gnu.org/software/guile/manual/html_node/Using-Guile-Modules.html)
[SRFI 26: Notation for Specializing Parameters without Currying](https://srfi.schemers.org/srfi-26/srfi-26.html)
[Top (Geiser User Manual)](https://www.nongnu.org/geiser/)
[Newspeak](https://newspeaklanguage.org/)
[Distributed Electronic Rights in JavaScript - Agoric](https://papers.agoric.com/papers/distributed-electronic-rights-in-javascript/abstract/)
[LNCS 7792 - Distributed Electronic Rights in JavaScript](https://papers.agoric.com/assets/pdf/papers/distributed-electronic-rights-in-javascript.pdf)
[Jitsi Meet](https://meet.jit.si/)
[Processes (Guile Reference Manual)](https://www.gnu.org/software/guile/manual/html_node/Processes.html)
